// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20220422183131_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Color")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4");

                    b.Property<string>("PetType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            Breed = "Persian",
                            Color = "White",
                            Gender = "Female",
                            Name = "Fluffy",
                            PetType = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 5,
                            Breed = "Persian",
                            Color = "White",
                            Gender = "Male",
                            Name = "Skittles",
                            PetType = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 9,
                            Breed = "Scotish Fold",
                            Color = "Grey",
                            Gender = "Male",
                            Name = "Burger",
                            PetType = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 8,
                            Breed = "Husky",
                            Color = "Black and White",
                            Gender = "Male",
                            Name = "Loki",
                            PetType = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 12,
                            Breed = "Husky",
                            Color = "Black and White",
                            Gender = "Female",
                            Name = "Naiya",
                            PetType = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 2,
                            Breed = "Husky",
                            Color = "Red",
                            Gender = "Male",
                            Name = "Copper",
                            PetType = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 1,
                            Breed = "Corgi",
                            Color = "Brown and White",
                            Gender = "Male",
                            Name = "Peanut Butter",
                            PetType = "Dog"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 2,
                            Breed = "Calico",
                            Color = "Brown and White",
                            Gender = "Female",
                            Name = "Cally",
                            PetType = "Cat"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 5,
                            Breed = "Pomeranian",
                            Color = "Black",
                            Gender = "Female",
                            Name = "Princess",
                            PetType = "Dog"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 7,
                            Breed = "Maine Coon",
                            Color = "Black and Brown",
                            Gender = "Male",
                            Name = "Pringles",
                            PetType = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
